routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('personal', 'PersonalController');
Route::resource('empresa', 'EmpresaController');

Route::group(['middleware' => 'auth'], function () {
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Models/Empresa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
    protected $table = 'empresa';
    protected $primaryKey = 'cuit';
    protected $keyType = 'string';
    public $timestamps = false;
    protected $fillable = array('cuit', 'razon', 'telefono', 'f_ini_acti', 'situacion_revista', 'condicion', 'actividad', 'cod_zona', 'mod_cotrata', 'tipo_empre', 'id_domicilio');
    protected $attributes = [
        'activo' => 1,
    ];
}

app/Http/Controllers/EmpresaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Empresa;
use App\Models\Domicilio;
use App\Models\SituacionRevista;
use App\Models\Condicion;
use App\Models\Actividad;
use App\Models\Siap_TiposModalidadesContratacion;

class EmpresaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['empresas'] = Empresa::all();
        return view('empresas/list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['situacionesRevista'] = SituacionRevista::all();
        $data['condiciones'] = Condicion::all();
        $data['actividades'] = Actividad::all();
        $data['modalidadesDeContratacion'] = Siap_TiposModalidadesContratacion::all();
        return view('empresas/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $domicilio = new Domicilio($data);
        $domicilio->save();
        $data['id_domicilio'] = $domicilio->id_domicilio;
        $empresa = new Empresa($data);
        $empresa->save();
        return redirect()->route('empresa.index')->withStatus('Empresa creada correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/empresas/create.blade.php
@extends('layouts.app', ['title' => 'Empresas'])

@section('content')
    @include('layouts.headers.crud-header', ['title' => 'Crear empresa'])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Empresas</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('empresa.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('empresa.store') }}" autocomplete="off">
                            @csrf
                            <h6 class="heading-small text-muted mb-4">Información de la empresa</h6>
                            <div class="row pl-lg-4">
                                @input(['name' => 'cuit', 'label' => 'CUIT','class' => 'col-md-6'])
                                @endinput

                                @input(['name' => 'razon', 'label' => 'Razón Social','class' => 'col-md-6'])
                                @endinput

                                @input(['name' => 'telefono', 'label' => 'Teléfono','class' => 'col-md-4'])
                                @endinput

                                @input(['name' => 'f_ini_acti', 'label' => 'Inicio de actividad','type'=>'date','class' => 'col-md-4'])
                                @endinput

                                @select(['name' => 'situacion_revista', 'label' => 'Situación revista','options'=>$situacionesRevista,'optionValue'=>'codigo','optionText'=> 'descripcion','class' => 'col-md-4'])
                                @endselect

                                @select(['name' => 'condicion', 'label' => 'Condición','options'=>$condiciones,'optionValue'=>'codigo','optionText'=> 'descripcion','class' => 'col-md-4'])
                                @endselect

                                @select(['name' => 'actividad', 'label' => 'Actividad','options'=>$actividades,'optionValue'=>'codigo','optionText'=> 'descripcion','class' => 'col-md-4'])
                                @endselect

                                @input(['name' => 'cod_zona', 'label' => 'Código de zona','type'=>'number','class' => 'col-md-4'])
                                @endinput

                                @select(['name' => 'mod_cotrata', 'label' => 'Modalidad de contratación','options'=>$modalidadesDeContratacion,'optionValue'=>'codigo','optionText'=> 'descripcion','class' => 'col-md-6'])
                                @endselect

                                @php
                                    $tiposEmpresa = [
                                        (Object)['codigo'=> 0,'descripcion' => 'E'],
                                        (Object)['codigo'=> 1,'descripcion' => 'L']
                                    ];
                                @endphp
                                @select(['name' => 'tipo_empre', 'label' => 'Tipo de empresa','options'=>$tiposEmpresa,'optionValue'=>'codigo','optionText'=> 'descripcion','class' => 'col-md-6'])
                                @endselect
                            </div>
                            <h6 class="heading-small text-muted mb-4">Domicilio</h6>
                            <div class="row pl-lg-4">
                                @input(['name' => 'calle', 'label' => 'Calle','class' => 'col-md-3']) @endinput
                                @input(['name' => 'numero', 'label' => 'Número','class' => 'col-md-3']) @endinput
                                @input(['name' => 'piso', 'label' => 'Piso','class' => 'col-md-3']) @endinput
                                @input(['name' => 'dpto', 'label' => 'Dpto','class' => 'col-md-3']) @endinput
                                @input(['name' => 'cod_postal', 'label' => 'Cod. Postal','class' => 'col-md-3']) @endinput
                                <div class="form-group col-md-3">
                                    <label class="form-control-label" >País</label>
                                    <select class="form-control" name="nacion">
                                        <option>Seleccionar</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label class="form-control-label" >Provincia</label>
                                    <select class="form-control" name="provincia">
                                        <option>Seleccionar</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label class="form-control-label" >Departamento</label>
                                    <select class="form-control" name="dep_partid">
                                        <option>Seleccionar</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label class="form-control-label" >Localidad</label>
                                    <select class="form-control" name="localidad">
                                        <option>Seleccionar</option>
                                    </select>
                                </div>
                                <div class="text-center col-md-12">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection

@push('js')
    <script>
        var selectNacion = $("select[name='nacion']");
        var selectProvincia = $("select[name='provincia']");
        var selectDepartamento = $("select[name='dep_partid']");
        var selectLocalidad = $("select[name='localidad']");

        $(function() {
            getPaises();
            selectNacion.change(function() {
                getProvincias(selectNacion.val());
            });
            selectProvincia.change(function() {
                getDepartamentos(selectProvincia.val());
            });
            selectDepartamento.change(function() {
                getLocalidades(selectDepartamento.val());
            });
        });

        function getPaises() {
            selectNacion.children('option:not(:first)').remove();
            $.get("{{ url('/api/domicilio/getPaises') }}", function( data ) {
                $.each(data ,function(key, value)
                {
                    selectNacion.append('<option value=' + value.pais + '>' + value.nombre + '</option>');
                });
            });
        }

        function getProvincias(pIdPais) {
            selectProvincia.children('option:not(:first)').remove();
            $.get("{{ url('/api/domicilio/getProvincias') }}" + '/' + pIdPais, function( data ) {
                $.each(data ,function(key, value)
                {
                    selectProvincia.append('<option value=' + value.provincia + '>' + value.nombre + '</option>');
                });
            });
        }

        function getDepartamentos(pIdProvincia) {
            selectDepartamento.children('option:not(:first)').remove();
            $.get("{{ url('/api/domicilio/getDepartamentos') }}" + '/' + pIdProvincia, function( data ) {
                $.each(data ,function(key, value)
                {
                    selectDepartamento.append('<option value=' + value.dpto_partido + '>' + value.nombre + '</option>');
                });
            });
        }

        function getLocalidades(pIdDepartamento) {
            selectLocalidad.children('option:not(:first)').remove();
            $.get("{{ url('/api/domicilio/getLocalidades') }}" + '/' + pIdDepartamento, function( data ) {
                $.each(data ,function(key, value)
                {
                    selectLocalidad.append('<option value=' + value.localidad + '>' + value.nombre + '</option>');
                });
            });
        }
    </script>
@endpush

resources/views/empresas/list.blade.php
@extends('layouts.app', ['title' => "Empresas"])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Empresas</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('empresa.create') }}" class="btn btn-sm btn-primary">Agregar empresa</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Tipo</th>
                                    <th scope="col">Razón social</th>
                                    <th scope="col">C.U.I.T</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($empresas as $empresa)
                                <tr>
                                    <td> {{ $empresa->tipo_empre }} </td>
                                    <td> {{ $empresa->razon }} </td>
                                    <td> {{ $empresa->cuit }} </td>
                                    <td class="text-right">
                                        @php $opciones = [ ['ruta' => route('empresa.edit', $empresa),'texto'=> 'Editar'] ] @endphp
                                        @botonEditar(['opciones'=>$opciones])
                                        @endbotonEditar
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        @include('layouts.footers.auth')
    </div>
@endsection